# frozen_string_literal: true

source 'https://rubygems.org'

# we can specify ruby version here
ruby '>= 2.3.4', '< 2.5'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 4.2'
gem 'sqlite3'
gem 'devise-multi_email'

gem 'devise'
gem 'jbuilder'

# Use SCSS for stylesheets
gem 'coffee-rails'
gem 'erb2haml'
gem 'haml-rails'
gem 'jquery-rails'
gem 'less-rails'
gem 'sass-rails'
gem 'therubyracer'
gem 'twitter-bootstrap-rails', '~> 2.2'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

group :development do
  gem 'pry'
  gem 'pry-byebug'
end
